pipeline {
    agent any

    stages {
        stage('Prepare') {
            steps {
                echo 'Setting up virtual environment and dependencies...'
                dir('new_project') {
                    sh 'python3 -m venv robot_env'
                    sh './robot_env/bin/pip install -r requirements.txt'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('new_project') {
                    sh './robot_env/bin/robot -d results tests/'
                }
            }
        }

        stage('Publish Reports') {
            steps {
                dir('new_project') {
                    publishHTML(target: [
                        reportDir: 'results',
                        reportFiles: 'log.html, report.html',
                        reportName: 'Robot Framework Report'
                    ])
                }
            }
        }
    }
}
